Repository woowacourse-teams/2023-naaga, pull requests merged in 2023-11, with the labels that each got.

#544 refactor: 도전 실패 반응 확인 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
Labels: 🦄 안드로이드, 빅스💻

#513 refactor: letter패키지 정리하기
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/letter/application/LetterFindService.java
  backend/src/main/java/com/now/naaga/letter/application/LetterService.java
  backend/src/main/java/com/now/naaga/letter/application/WriteLetterLogCreateService.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/ReadLetterLogService.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/WriteLetterLogService.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterByGameCommand.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterLogCreateCommand.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/WriteLetterLogCreateCommand.java
  backend/src/main/java/com/now/naaga/letter/domain/letterlog/LetterLogType.java
  backend/src/main/java/com/now/naaga/letter/domain/letterlog/ReadLetterLog.java
  backend/src/main/java/com/now/naaga/letter/exception/LetterExceptionType.java
  backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
  backend/src/main/java/com/now/naaga/letter/presentation/LetterLogController.java
  backend/src/main/java/com/now/naaga/letter/presentation/LogType.java
  backend/src/main/java/com/now/naaga/letter/presentation/converter/LetterLogTypeConverter.java
  backend/src/main/java/com/now/naaga/letter/presentation/dto/FindLetterLogByGameCommand.java
  backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
  backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
  backend/src/test/java/com/now/naaga/letter/application/letterlog/ReadLetterLogServiceTest.java
  backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
  backend/src/test/java/com/now/naaga/letter/presentation/LetterLogControllerTest.java
Labels: 🍀 백엔드, 6차 데모데이

#539 fix: 장소 추천의 상한과 하한 조정
  backend/src/main/java/com/now/naaga/place/domain/PlaceRecommendService.java
  backend/src/main/java/com/now/naaga/place/repository/PlaceRepository.java
  backend/src/test/java/com/now/naaga/common/fixture/PositionFixture.java
  backend/src/test/java/com/now/naaga/game/application/GameServiceTest.java
  backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
  backend/src/test/java/com/now/naaga/place/service/PlaceServiceTest.java
Labels: 🍀 백엔드, D-0

#547 feat: 좋아요, 싫어요 버튼을 연속 클릭할 수 없도록 변경
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/PreferenceView.kt
Labels: 🦄 안드로이드, D-0, 뽀또🍪

#540 feat: 빈 쪽지 검증 추가
  backend/build.gradle
  backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
  backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
  backend/src/main/java/com/now/naaga/letter/presentation/dto/LetterRequest.java
  backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
Labels: 🍀 백엔드, D-1

#542 feat: 빈 쪽지 못남기게 하는 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 크롱🦖

#541 feat: 읽은 쪽지 로그 중복 쪽지 제거
  backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
  backend/src/main/java/com/now/naaga/letter/application/LetterService.java
  backend/src/main/java/com/now/naaga/letter/repository/letterlog/ReadLetterLogRepository.java
  backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
Labels: 🍀 백엔드, D-1

#467 feat: 커스텀 버튼 제작
  android/app/src/main/java/com/now/naaga/presentation/custom/GameButton.kt
  android/app/src/main/java/com/now/naaga/presentation/custom/GameButtonColor.kt
  android/app/src/main/res/drawable/bg_blue_button.xml
  android/app/src/main/res/drawable/bg_yellow_button.xml
  android/app/src/main/res/drawable/bg_yellow_button_thick.xml
  android/app/src/main/res/layout/activity_adventure_result.xml
  android/app/src/main/res/layout/activity_begin_adventure.xml
  android/app/src/main/res/layout/activity_my_page.xml
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/layout/activity_upload.xml
  android/app/src/main/res/values-night/colors.xml
  android/app/src/main/res/values/attrs.xml
  android/app/src/main/res/values/colors.xml
Labels: 🦄 안드로이드, D-2, 뽀또🍪, 크롱🦖, 6차 데모데이

#559 feat: 읽을 수 없는 쪽지 삭제
  android/app/src/main/java/com/now/naaga/presentation/onadventure/NaverMapSettingDelegate.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/res/drawable/ic_letter_preview.xml
  android/domain/build.gradle
Labels: 🦄 안드로이드, 뽀또🍪

#557 refactor: 테스트 실행 속도 개선 및 중복 코드 제거
  backend/src/test/java/com/now/naaga/NaagaApplicationTests.java
  backend/src/test/java/com/now/naaga/auth/application/AuthServiceTest.java
  backend/src/test/java/com/now/naaga/auth/presentation/AuthControllerTest.java
  backend/src/test/java/com/now/naaga/auth/presentation/AuthInterceptorTest.java
  backend/src/test/java/com/now/naaga/auth/presentation/PlayerArgumentResolverTest.java
  backend/src/test/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptorTest.java
  backend/src/test/java/com/now/naaga/common/AbstractTest.java
  backend/src/test/java/com/now/naaga/common/CommonControllerTest.java
  backend/src/test/java/com/now/naaga/common/ControllerTest.java
  backend/src/test/java/com/now/naaga/common/ServiceTest.java
  backend/src/test/java/com/now/naaga/game/application/GameServiceTest.java
  backend/src/test/java/com/now/naaga/game/application/HintServiceTest.java
  backend/src/test/java/com/now/naaga/game/domain/GameTest.java
  backend/src/test/java/com/now/naaga/game/domain/ResultScorePolicyTest.java
  backend/src/test/java/com/now/naaga/game/domain/StatisticTest.java
  backend/src/test/java/com/now/naaga/game/domain/gamescore/ResultScoreCalculatorTest.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
  backend/src/test/java/com/now/naaga/game/presentation/StatisticControllerTest.java
  backend/src/test/java/com/now/naaga/gameresult/application/GameResultServiceTest.java
  backend/src/test/java/com/now/naaga/gameresult/repository/GameResultRepositoryTest.java
  backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
  backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
  backend/src/test/java/com/now/naaga/like/application/PlaceLikeServiceTest.java
  backend/src/test/java/com/now/naaga/like/domain/PlaceLikeTest.java
  backend/src/test/java/com/now/naaga/like/presentation/PlaceLikeControllerTest.java
  backend/src/test/java/com/now/naaga/member/persistence/repository/MemberRepositoryTest.java
  backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
  backend/src/test/java/com/now/naaga/place/application/PlaceStatisticsServiceTest.java
  backend/src/test/java/com/now/naaga/place/domain/PlaceStatisticsTest.java
  backend/src/test/java/com/now/naaga/place/presentation/PlaceControllerTest.java
  backend/src/test/java/com/now/naaga/player/application/PlayerServiceTest.java
  backend/src/test/java/com/now/naaga/player/persistence/repository/PlayerRepositoryTest.java
  backend/src/test/java/com/now/naaga/player/presentation/PlayerControllerTest.java
  backend/src/test/java/com/now/naaga/temporaryplace/application/TemporaryPlaceServiceTest.java
  backend/src/test/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceControllerTest.java
Labels: 🍀 백엔드, D-0

#563 feat: 플레이어 정보 조회 기능 구현
  backend/src/main/java/com/now/naaga/player/presentation/PlayerController.java
  backend/src/test/java/com/now/naaga/player/presentation/PlayerControllerTest.java
Labels: 🍀 백엔드, D-0

#566 feat: 닉네임 변경 API 구현
  backend/src/main/java/com/now/naaga/player/application/PlayerService.java
  backend/src/main/java/com/now/naaga/player/application/dto/EditPlayerNicknameCommand.java
  backend/src/main/java/com/now/naaga/player/domain/Player.java
  backend/src/main/java/com/now/naaga/player/exception/PlayerExceptionType.java
  backend/src/main/java/com/now/naaga/player/persistence/repository/PlayerRepository.java
  backend/src/main/java/com/now/naaga/player/presentation/PlayerController.java
  backend/src/main/java/com/now/naaga/player/presentation/dto/EditPlayerRequest.java
  backend/src/main/java/com/now/naaga/player/presentation/dto/EditPlayerResponse.java
  backend/src/test/java/com/now/naaga/common/fixture/PlayerFixture.java
  backend/src/test/java/com/now/naaga/player/application/PlayerServiceTest.java
  backend/src/test/java/com/now/naaga/player/domain/PlayerTest.java
  backend/src/test/java/com/now/naaga/player/presentation/PlayerControllerTest.java
Labels: 🍀 백엔드, D-0

#565 refactor: 사용자 주변 쪽지 조회 범위 수정
  backend/src/main/java/com/now/naaga/letter/application/LetterService.java
Labels: 🍀 백엔드, D-0

#571 feat: 인게임 쪽지에 등록자와 등록 시간 보여주기
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/LetterReadDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/res/layout/dialog_read_letter.xml
Labels: 🦄 안드로이드, 크롱🦖

#569 feat: 닉네임 변경 기능 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/remote/dto/NicknameDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/ProfileService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultProfileRepository.kt
  android/app/src/main/java/com/now/naaga/di/RepositoryModule.kt
  android/app/src/main/java/com/now/naaga/di/ServiceModule.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/profile/ProfileActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/profile/ProfileViewModel.kt
  android/app/src/main/res/drawable/ic_profile_modify.xml
  android/app/src/main/res/drawable/rect_border.xml
  android/app/src/main/res/layout/activity_my_page.xml
  android/app/src/main/res/layout/activity_profile.xml
  android/app/src/main/res/layout/activity_upload.xml
  android/app/src/main/res/layout/rv_mypage_item_adventure.xml
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/repository/ProfileRepository.kt
Labels: 🦄 안드로이드, 빅스💻

#567 feat: 좋아요 수 집계에 대한 동시성 문제 해결
  backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
  backend/src/main/java/com/now/naaga/place/application/PlaceStatisticsService.java
  backend/src/main/java/com/now/naaga/place/domain/PlaceStatistics.java
  backend/src/main/java/com/now/naaga/place/repository/PlaceStatisticsRepository.java
  backend/src/test/java/com/now/naaga/like/application/PlaceLikeServiceTest.java
Labels: 🍀 백엔드, D-0
