Repository woowacourse-teams/2023-naaga, pull requests merged in 2023-08, with the labels that each got.

#116 [AN] feat: 통계 path api 목서버 구현
  android/app/src/main/java/com/now/naaga/StatisticsMockWeb.kt
Labels: 🦄 안드로이드, 3차 데모데이

#117 [AN] feat: 랭크 path api 목서버 구현
  android/app/src/main/java/com/now/naaga/RankMockWeb.kt
Labels: 🦄 안드로이드, 3차 데모데이

#119 [AN] feat: RankActivity 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/presentation/rank/RankActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/recyclerview/RankAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/recyclerview/RankViewHolder.kt
  android/app/src/main/res/layout/activity_rank.xml
  android/app/src/main/res/layout/item_rank.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 3차 데모데이

#120 [AN] feat: 카메라로 찍은 사진을 뷰에 띄우고 Uri 추출기능 구현
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/res/layout/activity_upload.xml
Labels: 🦄 안드로이드, 3차 데모데이

#121 [AN] feat: MyPageActivity 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/RankDto.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageCustomGrid.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageItemUiModel.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
  android/app/src/main/res/drawable/oval.xml
  android/app/src/main/res/layout/activity_my_page.xml
  android/app/src/main/res/layout/custom_mypage_grid.xml
  android/app/src/main/res/layout/rv_mypage_item_place.xml
  android/app/src/main/res/layout/rv_mypage_item_statistics.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/model/Rank.kt
  android/domain/src/main/java/com/now/domain/model/RestTryCount.kt
Labels: 🦄 안드로이드, 3차 데모데이

#134 [BE] refactor: Pull Request 워크플로우 수정
  .github/workflows/backend_dev_pr_workflow.yml
Labels: 🍀 백엔드, 3차 데모데이

#136 [BE] refactor: DTO들이 모두 record로 구현되도록 수정
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/application/dto/FindGameByIdCommand.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameResponse.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameStatusResponse.java
  backend/src/main/java/com/now/naaga/member/application/dto/MemberCommand.java
  backend/src/main/java/com/now/naaga/place/presentation/dto/PlaceResponse.java
Labels: 🍀 백엔드, 3차 데모데이

#137 [BE] feat: merge 워크 플로우 추가
  .github/workflows/backend_dev_merge_workflow.yml
  backend/Dockerfile
Labels: 🍀 백엔드, 3차 데모데이

#139 [BE] refactor: merge 워크 플로우 추가
  .github/workflows/backend_dev_merge_workflow.yml
  backend/Dockerfile
Labels: 🍀 백엔드, 3차 데모데이

#94 [BE] feat: 랭크 조회 기능 구현
  backend/build.gradle
  backend/src/main/java/com/now/naaga/member/application/dto/MemberCommand.java
  backend/src/main/java/com/now/naaga/member/presentation/dto/MemberAuthRequest.java
  backend/src/main/java/com/now/naaga/player/application/PlayerService.java
  backend/src/main/java/com/now/naaga/player/domain/Rank.java
  backend/src/main/java/com/now/naaga/player/exception/PlayerExceptionType.java
  backend/src/main/java/com/now/naaga/player/presentation/PlayerController.java
  backend/src/main/java/com/now/naaga/player/presentation/dto/PlayerResponse.java
  backend/src/main/java/com/now/naaga/player/presentation/dto/RankResponse.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/test/java/com/now/naaga/acceptance/ControllerTest.java
  backend/src/test/java/com/now/naaga/acceptance/player/PlayerControllerTest.java
  backend/src/test/java/com/now/naaga/config/infrastructure/BasicAuthenticationDecoderTest.java
  backend/src/test/java/com/now/naaga/member/persistence/repository/MemberRepositoryTest.java
  backend/src/test/java/com/now/naaga/player/application/PlayerServiceTest.java
  backend/src/test/java/com/now/naaga/player/persistence/repository/PlayerRepositoryTest.java
  backend/src/test/resources/truncate.sql
Labels: 🍀 백엔드, 3차 데모데이

#138 [AN] feat: 랭크 뷰 기능 구현 및 서버 통신 구현
  android/app/src/main/java/com/now/naaga/RankMockWeb.kt
  android/app/src/main/java/com/now/naaga/StatisticsMockWeb.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/RankDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitFactory.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/RankService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultRankRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
  android/app/src/main/res/layout/activity_rank.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 3차 데모데이

#143 [AN] feat: 게임 결과 뷰 서버 통신 및 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/res/drawable/ic_none_photo.xml
  android/app/src/main/res/layout/activity_adventure_result.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 3차 데모데이

#151 [AN] feat: 모험 기록 뷰 기능 구현 및 서버 통신 구현
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryViewHolder.kt
  android/app/src/main/res/layout/activity_adventure_history.xml
  android/app/src/main/res/layout/item_history.xml
Labels: 🦄 안드로이드, 3차 데모데이

#152 [BE] feat: 게임 결과 조회 기능 구현
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/domain/Game.java
  backend/src/main/java/com/now/naaga/game/domain/GameRecord.java
  backend/src/main/java/com/now/naaga/game/domain/GameResult.java
  backend/src/main/java/com/now/naaga/game/exception/GameExceptionType.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/CoordinateResponse.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameDestinationResponse.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameResultResponse.java
  backend/src/main/java/com/now/naaga/game/repository/GameRepository.java
  backend/src/main/java/com/now/naaga/game/repository/GameResultRepository.java
  backend/src/test/java/com/now/naaga/acceptance/game/GameControllerTest.java
Labels: 🍀 백엔드, 3차 데모데이

#154 [BE] feat: 장소 등록 api 구현
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/common/domain/OrderType.java
  backend/src/main/java/com/now/naaga/common/exception/CommonException.java
  backend/src/main/java/com/now/naaga/common/exception/CommonExceptionType.java
  backend/src/main/java/com/now/naaga/common/infrastructure/FileManager.java
  backend/src/main/java/com/now/naaga/common/infrastructure/MultipartFileManager.java
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/domain/Hint.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/place/application/PlaceService.java
  backend/src/main/java/com/now/naaga/place/application/dto/CreatePlaceCommand.java
  backend/src/main/java/com/now/naaga/place/application/dto/FindAllPlaceCommand.java
  backend/src/main/java/com/now/naaga/place/application/dto/FindPlaceByIdCommand.java
  backend/src/main/java/com/now/naaga/place/application/dto/RecommendPlaceCommand.java
  backend/src/main/java/com/now/naaga/place/domain/Place.java
  backend/src/main/java/com/now/naaga/place/domain/PlaceCheckService.java
  backend/src/main/java/com/now/naaga/place/domain/PlaceRecommendService.java
  backend/src/main/java/com/now/naaga/place/domain/Position.java
  backend/src/main/java/com/now/naaga/place/domain/SortType.java
  backend/src/main/java/com/now/naaga/place/exception/PlaceExceptionType.java
  backend/src/main/java/com/now/naaga/place/persistence/repository/PlaceRepository.java
  backend/src/main/java/com/now/naaga/place/presentation/PlaceController.java
  backend/src/main/java/com/now/naaga/place/presentation/dto/CoordinateResponse.java
  backend/src/main/java/com/now/naaga/place/presentation/dto/CreatePlaceRequest.java
  backend/src/main/java/com/now/naaga/place/presentation/dto/PlaceResponse.java
  backend/src/main/java/com/now/naaga/player/domain/Player.java
  backend/src/main/java/com/now/naaga/player/presentation/PlayerController.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.properties
  backend/src/test/java/com/now/naaga/acceptance/ControllerTest.java
  backend/src/test/java/com/now/naaga/acceptance/game/GameControllerTest.java
  backend/src/test/java/com/now/naaga/common/CommonControllerTest.java
  backend/src/test/java/com/now/naaga/config/infrastructure/BasicAuthenticationDecoderTest.java
  backend/src/test/java/com/now/naaga/game/application/GameServiceTest.java
  backend/src/test/java/com/now/naaga/game/domain/GameTest.java
  backend/src/test/java/com/now/naaga/game/domain/ScorePolicyTest.java
  backend/src/test/java/com/now/naaga/game/fixture/GameFixture.java
  backend/src/test/java/com/now/naaga/game/fixture/GameResultFixture.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
  backend/src/test/java/com/now/naaga/member/fixture/MemberFixture.java
  backend/src/test/java/com/now/naaga/member/persistence/repository/MemberRepositoryTest.java
  backend/src/test/java/com/now/naaga/place/fixture/PlaceFixture.java
  backend/src/test/java/com/now/naaga/place/fixture/PositionFixture.java
  backend/src/test/java/com/now/naaga/place/fixture/루터회관.png
  backend/src/test/java/com/now/naaga/place/presentation/PlaceControllerTest.java
  backend/src/test/java/com/now/naaga/player/application/PlayerServiceTest.java
  backend/src/test/java/com/now/naaga/player/fixture/PlayerFixture.java
  backend/src/test/java/com/now/naaga/player/persistence/repository/PlayerRepositoryTest.java
  backend/src/test/java/com/now/naaga/player/presentation/PlayerControllerTest.java
  backend/src/test/java/com/now/naaga/score/fixture/ScoreFixture.java
  backend/src/test/resources/truncate.sql
Labels: 🍀 백엔드, 3차 데모데이

#157 [BE] feat: 특정 게임의 힌트 단건 조회 API 설계 및 구현
  backend/src/main/java/com/now/naaga/game/application/HintService.java
  backend/src/main/java/com/now/naaga/game/application/dto/FindHintByIdCommand.java
  backend/src/main/java/com/now/naaga/game/domain/Hint.java
  backend/src/main/java/com/now/naaga/game/exception/GameExceptionType.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/DirectionResponse.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/HintResponse.java
  backend/src/test/java/com/now/naaga/game/application/HintServiceTest.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
  backend/src/test/java/com/now/naaga/member/fixture/MemberFixture.java
Labels: 🍀 백엔드, 3차 데모데이

#149 [AN] feat: 인게임 화면 기능 및 서버통신 구현
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/AdventureStatusDto.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/AdventureThrowable.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/DisposableLiveData.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/NaagaAlertDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/NaverMapSettingDelegate.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/featureList.md
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModelFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/AdventureMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/HintMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/PlaceMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/PlayerMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/GameUiModel.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/HintUiModel.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/PlaceUiModel.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/PlayerUiModel.kt
  android/app/src/main/res/drawable/ic_marker_east.xml
  android/app/src/main/res/drawable/ic_marker_north.xml
  android/app/src/main/res/drawable/ic_marker_south.xml
  android/app/src/main/res/drawable/ic_marker_west.xml
  android/app/src/main/res/drawable/rect_radius_small_bottom_left.xml
  android/app/src/main/res/drawable/rect_radius_small_bottom_right.xml
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/layout/dialog_naaga_alert.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/model/Place.kt
Labels: 🦄 안드로이드, 3차 데모데이

#156 [AN] feat: 점진적 리팩토링이 완료됨에 따라 파일 정리
  android/app/src/main/java/com/now/naaga/data/mapper/AdventureMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/AdventureResultMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/DestinationMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/HintMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/PlaceMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/PlayerMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/RankMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/StatisticsMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureResultDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureStatusDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/DestinationDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/FinishGameDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/HintDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/PlaceDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/PlayerDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/RankDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/StatisticsDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/GameDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/Adventure2Service.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/RankService.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/StatisticsService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/MockAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/ThirdDemoAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/featureList.md
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/AdventureMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/DestinationMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/AdventureUiModel.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/DestinationUiModel.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/GameUiModel.kt
  android/domain/src/main/java/com/now/domain/model/Adventure.kt
  android/domain/src/main/java/com/now/domain/model/Game.kt
  android/domain/src/main/java/com/now/domain/repository/AdventureRepository.kt
  android/domain/src/main/java/com/now/domain/repository/AdventureRepository2.kt
Labels: 🦄 안드로이드, 3차 데모데이

#159 [BE] feat: 통계 조회 기능 구현
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/domain/GameRecord.java
  backend/src/main/java/com/now/naaga/game/domain/Statistic.java
  backend/src/main/java/com/now/naaga/game/presentation/StatisticController.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameResultResponse.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/StatisticResponse.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
  backend/src/test/java/com/now/naaga/game/presentation/StatisticControllerTest.java
Labels: 🍀 백엔드, 3차 데모데이

#161 [BE] fix: 인터셉터 패턴 추가(#160)
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/resources/data.sql
Labels: 🍀 백엔드, 3차 데모데이

#162 [AN] feat: 게임 시작 화면 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 3차 데모데이

#166 [BE] feat: 게임 생성 로직 수정
  backend/src/main/java/com/now/naaga/game/domain/Game.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameResponse.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/HintResponse.java
  backend/src/main/java/com/now/naaga/place/domain/PlaceRecommendService.java
  backend/src/test/java/com/now/naaga/common/CommonControllerTest.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
Labels: 🍀 백엔드, 3차 데모데이

#170 [AN] feat: firebase crashlytics 초기 환경 설정
  android/app/build.gradle
  android/build.gradle
Labels: 🦄 안드로이드, 3차 데모데이

#171 [AN] feat: Firebase Analytics 생성 및 로그 삽입을 위한 객체 구현
  android/app/build.gradle
  android/app/src/main/java/com/now/naaga/data/firebase/analytics/AnalyticsDelegate.kt
  android/app/src/main/java/com/now/naaga/data/firebase/analytics/ButtonNames.kt
  android/app/src/main/java/com/now/naaga/data/firebase/analytics/ServerErrorNames.kt
Labels: 🦄 안드로이드, 3차 데모데이

#174 [BE] fix: application.properties 복구
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.properties
Labels: 🍀 백엔드, 3차 데모데이

#176 [BE] chore: 인메모리 더미 데이터 추가
  backend/src/main/resources/data.sql
Labels: 🍀 백엔드, 3차 데모데이

#177 [AN] feat: API 수정으로 인한 변경사항 적용
  android/app/src/main/java/com/now/naaga/data/mapper/AdventureResultMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/StatisticsMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureResultDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/StatisticsDto.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageMapper.kt
  android/app/src/main/res/layout/activity_adventure_result.xml
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/model/AdventureResult.kt
  android/domain/src/main/java/com/now/domain/model/Statistics.kt
Labels: 🦄 안드로이드, 3차 데모데이

#179 [BE] refactor: RankReponse 수정
  backend/src/main/java/com/now/naaga/player/domain/Rank.java
  backend/src/main/java/com/now/naaga/player/presentation/dto/RankResponse.java
  backend/src/test/java/com/now/naaga/player/application/PlayerServiceTest.java
  backend/src/test/java/com/now/naaga/player/presentation/PlayerControllerTest.java
Labels: 🍀 백엔드, 3차 데모데이

#182 [AN] feat: baseUrl 변경 및 감추기와 그에 따른 yml 파일 변경
  .github/workflows/android_ci.yml
  android/app/build.gradle
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitFactory.kt
Labels: 🦄 안드로이드, 3차 데모데이

#181 [AN] feat: 업로드 뷰 기능 구현
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
  android/app/src/main/res/layout/activity_upload.xml
  android/domain/src/main/java/com/now/domain/repository/PlaceRepository.kt
Labels: 🦄 안드로이드, 3차 데모데이

#191 [BE] fix: 랭크 전체조회 쿼리 파라미터 조건 수정
  backend/src/main/java/com/now/naaga/player/presentation/PlayerController.java
Labels: 🍀 백엔드, 3차 데모데이

#192 [BE] fix: 장소데이터 추가 및 인터셉터 설정 변경
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/static/blakc-lab.jpeg
Labels: 🍀 백엔드, 3차 데모데이

#193 [BE] refactor: 게임 시작 요청의 requestbody 수정
  backend/src/main/java/com/now/naaga/game/application/dto/CreateGameCommand.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
Labels: 🍀 백엔드, 3차 데모데이

#195 [BE] fix: POST /games/{gameId}/hints 쿼리 스트링 없어도 되도록 수정
  backend/src/main/java/com/now/naaga/game/application/dto/CreateHintCommand.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameResultResponse.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
Labels: 🍀 백엔드, 3차 데모데이

#198 [BE] feat: 게임 종료 시, 플레이어 점수 덧셈 기능 추가
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameResultResponse.java
  backend/src/main/java/com/now/naaga/player/domain/Player.java
  backend/src/main/java/com/now/naaga/score/domain/Score.java
Labels: 🍀 백엔드, 3차 데모데이

#183 [AN] feat: Firebase Analytics 버튼 클릭 로그 추가
  android/app/src/main/java/com/now/naaga/data/firebase/analytics/AnalyticsDelegate.kt
  android/app/src/main/java/com/now/naaga/data/firebase/analytics/ButtonNames.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/LocationPermissionDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/CameraPermissionDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/res/layout/activity_on_adventure.xml
Labels: 🦄 안드로이드, 3차 데모데이

#196 [AN] fix: 서버 통신 수정
  android/app/src/main/java/com/now/naaga/data/NaagaThrowable.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureStatusDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/FailureDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitUtil.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/AdventureThrowable.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/DisposableLiveData.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
Labels: 🦄 안드로이드, 3차 데모데이

#239 [BE] fix: 깃허브 액션 워크플로우 수정
  .github/workflows/backend_dev_merge_workflow.yml
Labels: 🍀 백엔드, 4차 데모데이

#235 [AN] feat: 소셜 로그인 기능 구현
  .github/workflows/android_ci.yml
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/local/AuthDataSource.kt
  android/app/src/main/java/com/now/naaga/data/local/KakaoAuthDataSource.kt
  android/app/src/main/java/com/now/naaga/data/mapper/AuthMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/NaagaAuthDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/PlatformAuthDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitFactory.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AuthService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModelFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/login/NaagaApplication.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/util/UserApiClientExt.kt
  android/app/src/main/res/drawable/ic_kakao_login.png
  android/app/src/main/res/drawable/ic_logo_purple.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_my_page.xml
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/model/AuthPlatformType.kt
  android/domain/src/main/java/com/now/domain/model/NaagaAuth.kt
  android/domain/src/main/java/com/now/domain/model/PlatformAuth.kt
  android/domain/src/main/java/com/now/domain/repository/AuthRepository.kt
  android/settings.gradle
Labels: 🦄 안드로이드, 4차 데모데이

#234 [BE] chore: 오류 코드 정리 및 예외 핸들러 보완
  backend/src/main/java/com/now/naaga/auth/application/AuthService.java
  backend/src/main/java/com/now/naaga/auth/exception/AuthExceptionType.java
  backend/src/main/java/com/now/naaga/common/exception/CommonExceptionType.java
  backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/application/HintService.java
  backend/src/main/java/com/now/naaga/game/exception/GameExceptionType.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/member/exception/MemberExceptionType.java
  backend/src/main/java/com/now/naaga/place/domain/PlaceRecommendService.java
  backend/src/main/java/com/now/naaga/place/exception/PlaceExceptionType.java
  backend/src/main/java/com/now/naaga/player/exception/PlayerExceptionType.java
  backend/src/main/java/com/now/naaga/player/presentation/PlayerController.java
  backend/src/test/java/com/now/naaga/game/application/HintServiceTest.java
  backend/src/test/java/com/now/naaga/game/domain/DirectionTest.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
Labels: 🍀 백엔드, 4차 데모데이

#242 [BE] fix: 게임 종료 실패 시, 남은 도전 횟수 줄지 않는 문제 해결
  .github/workflows/backend_dev_pr_workflow.yml
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/domain/Game.java
  backend/src/main/java/com/now/naaga/game/exception/GameNotArrivalException.java
  backend/src/test/java/com/now/naaga/game/application/GameServiceRepositoryTest.java
  backend/src/test/java/com/now/naaga/game/application/GameServiceTest.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
Labels: 🍀 백엔드, 4차 데모데이

#241 [AN] feat: 자동 로그인 및 로그인 로직 수정
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/NaagaApplication.kt
  android/app/src/main/java/com/now/naaga/data/local/AuthDataSource.kt
  android/app/src/main/java/com/now/naaga/data/local/DefaultAuthDataSource.kt
  android/app/src/main/java/com/now/naaga/data/local/KakaoAuthDataSource.kt
  android/app/src/main/java/com/now/naaga/data/mapper/AuthMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/NaagaAuthDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitFactory.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AuthService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModelFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/login/NaagaApplication.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/util/KakaoLoginUtil.kt
  android/app/src/main/res/layout/activity_my_page.xml
  android/domain/src/main/java/com/now/domain/model/NaagaAuth.kt
  android/domain/src/main/java/com/now/domain/repository/AuthRepository.kt
Labels: 🦄 안드로이드, 3차 데모데이

#243 [AN] feat: 예외처리
  android/app/src/main/java/com/now/naaga/data/NaagaThrowable.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitUtil.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultRankRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultStatisticsRepository.kt
  android/app/src/main/java/com/now/naaga/data/throwable/DataThrowable.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/AdventureThrowable.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 4차 데모데이

#238 [BE] feat: 소셜 로그인 기능과 인터셉터 인가 처리 및 아규먼트 리졸버 기능 추가 (#216)
  backend/build.gradle
  backend/src/main/java/com/now/naaga/auth/application/AuthService.java
  backend/src/main/java/com/now/naaga/auth/application/dto/AuthCommand.java
  backend/src/main/java/com/now/naaga/auth/application/dto/AuthInfo.java
  backend/src/main/java/com/now/naaga/auth/domain/AuthTokens.java
  backend/src/main/java/com/now/naaga/auth/exception/AuthExceptionType.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/AuthClient.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/AuthType.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/BasicAuthenticationDecoder.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/BasicAuthenticationExtractor.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/BearerAuthExtractor.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/jwt/JwtGenerator.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/jwt/JwtProvider.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthArgumentResolver.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthController.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthInterceptor.java
  backend/src/main/java/com/now/naaga/auth/presentation/dto/AuthRequest.java
  backend/src/main/java/com/now/naaga/auth/presentation/dto/AuthResponse.java
  backend/src/main/java/com/now/naaga/common/config/BeanConfig.java
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/member/application/CreateMemberCommand.java
  backend/src/main/java/com/now/naaga/member/application/MemberService.java
  backend/src/main/java/com/now/naaga/member/domain/Member.java
  backend/src/main/java/com/now/naaga/member/presentation/dto/MemberAuthRequest.java
  backend/src/main/java/com/now/naaga/player/application/PlayerService.java
  backend/src/main/java/com/now/naaga/player/application/dto/CreatePlayerCommand.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/com/now/naaga/auth/application/AuthServiceTest.java
  backend/src/test/java/com/now/naaga/auth/presentation/AuthArgumentResolverTest.java
  backend/src/test/java/com/now/naaga/auth/presentation/AuthControllerTest.java
  backend/src/test/java/com/now/naaga/auth/presentation/AuthInterceptorTest.java
  backend/src/test/java/com/now/naaga/config/infrastructure/BasicAuthenticationDecoderTest.java
  backend/src/test/java/com/now/naaga/game/fixture/MemberFixture.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
  backend/src/test/java/com/now/naaga/game/presentation/StatisticControllerTest.java
  backend/src/test/java/com/now/naaga/member/fixture/MemberFixture.java
  backend/src/test/java/com/now/naaga/member/persistence/repository/MemberRepositoryTest.java
  backend/src/test/java/com/now/naaga/place/presentation/PlaceControllerTest.java
  backend/src/test/java/com/now/naaga/player/application/PlayerServiceTest.java
  backend/src/test/java/com/now/naaga/player/persistence/repository/PlayerRepositoryTest.java
  backend/src/test/java/com/now/naaga/player/presentation/PlayerControllerTest.java
Labels: 🍀 백엔드, 4차 데모데이

#245 [AN] feat: 난독화를 위해 모든 Dto 필드에 SerialName 추가
  android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureResultDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureStatusDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/CoordinateDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/EndedAdventureDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/FailureDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/FinishGameDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/HintDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/NaagaAuthDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/PlaceDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/PlatformAuthDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/PlayerDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/RankDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/StatisticsDto.kt
Labels: 🦄 안드로이드, 3차 데모데이

#247 fix: AuthInfo에 기본 생성자 추가
  backend/src/main/java/com/now/naaga/auth/application/dto/AuthInfo.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/AuthClient.java
Labels: 🍀 백엔드, 4차 데모데이

#253 [AN] feat: 앱 아이콘 설정
  .idea/2023-naaga.iml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/naaga_icon-playstore.png
  android/app/src/main/res/mipmap-anydpi-v26/naaga_icon.xml
  android/app/src/main/res/mipmap-anydpi-v26/naaga_icon_round.xml
  android/app/src/main/res/mipmap-hdpi/naaga_icon.png
  android/app/src/main/res/mipmap-hdpi/naaga_icon_foreground.png
  android/app/src/main/res/mipmap-hdpi/naaga_icon_round.png
  android/app/src/main/res/mipmap-mdpi/naaga_icon.png
  android/app/src/main/res/mipmap-mdpi/naaga_icon_foreground.png
  android/app/src/main/res/mipmap-mdpi/naaga_icon_round.png
  android/app/src/main/res/mipmap-xhdpi/naaga_icon.png
  android/app/src/main/res/mipmap-xhdpi/naaga_icon_foreground.png
  android/app/src/main/res/mipmap-xhdpi/naaga_icon_round.png
  android/app/src/main/res/mipmap-xxhdpi/naaga_icon.png
  android/app/src/main/res/mipmap-xxhdpi/naaga_icon_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/naaga_icon_round.png
  android/app/src/main/res/mipmap-xxxhdpi/naaga_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/naaga_icon_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/naaga_icon_round.png
  android/app/src/main/res/values/naaga_icon_background.xml
Labels: 🦄 안드로이드, 4차 데모데이

#255 [AN] fix: 메인으로 돌아갈 시 해당 액티비티가 사라지도록 수정
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
Labels: 🦄 안드로이드, 4차 데모데이

#258 [AN] feat: 사용자가 GPS 기능을 껐을 때 이를 인지하고 키도록 유도하는 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
Labels: 🦄 안드로이드, 4차 데모데이

#250 [AN] feat: 장치 구성 변경 대응
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/NaagaApplication.kt
Labels: 🦄 안드로이드, 4차 데모데이

#259 feat: 난독화 방지를 위한 ProGuard 수정
  android/app/build.gradle
  android/app/proguard-rules.pro
Labels: 🦄 안드로이드, 4차 데모데이

#260 [AN] feat: Firebase Analytics 서버 통신 에러 로그 추가
  android/app/src/main/java/com/now/naaga/data/firebase/analytics/ServerErrorNames.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
Labels: 🦄 안드로이드, 4차 데모데이

#263 [AN] feat: 이어하기 기능 추가
  android/.editorconfig
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/now/naaga/util/IntentExt.kt
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 4차 데모데이

#265 [AN] fix: OnAdventureActivity 수정
  android/app/build.gradle
  android/app/src/main/java/com/now/naaga/presentation/onadventure/DistinctChildLiveData.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/raw/animation_ll5gzgdu.json
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 4차 데모데이

#271 [AN] feat: 로그인 시 사용자의 토큰이 로그에 보여지지 않도록 수정
  android/app/src/main/java/com/now/naaga/util/KakaoLoginUtil.kt
Labels: 🦄 안드로이드, 4차 데모데이

#274 [AN] feat: 스플래시에서 받아온 게임을 넘겨주는 기능 삭제
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
Labels: 🦄 안드로이드, 4차 데모데이

#280 [BE] test: 테스트 fixture 및 builder 추가 및 적용
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameResultResponse.java
  backend/src/main/java/com/now/naaga/place/domain/Place.java
  backend/src/main/java/com/now/naaga/player/domain/Player.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/now/naaga/auth/presentation/AuthArgumentResolverTest.java
  backend/src/test/java/com/now/naaga/auth/presentation/AuthControllerTest.java
  backend/src/test/java/com/now/naaga/auth/presentation/AuthInterceptorTest.java
  backend/src/test/java/com/now/naaga/common/builder/GameBuilder.java
  backend/src/test/java/com/now/naaga/common/builder/GameResultBuilder.java
  backend/src/test/java/com/now/naaga/common/builder/MemberBuilder.java
  backend/src/test/java/com/now/naaga/common/builder/PlaceBuilder.java
  backend/src/test/java/com/now/naaga/common/builder/PlayerBuilder.java
  backend/src/test/java/com/now/naaga/common/fixture/MemberFixture.java
  backend/src/test/java/com/now/naaga/common/fixture/PlaceFixture.java
  backend/src/test/java/com/now/naaga/common/fixture/PlayerFixture.java
  backend/src/test/java/com/now/naaga/common/fixture/PositionFixture.java
  backend/src/test/java/com/now/naaga/game/application/HintServiceTest.java
  backend/src/test/java/com/now/naaga/game/domain/GameScorePolicyTest.java
  backend/src/test/java/com/now/naaga/game/domain/GameTest.java
  backend/src/test/java/com/now/naaga/game/domain/gamescore/GameScoreCalculatorTest.java
  backend/src/test/java/com/now/naaga/game/fixture/GameFixture.java
  backend/src/test/java/com/now/naaga/game/fixture/GameResultFixture.java
  backend/src/test/java/com/now/naaga/game/fixture/MemberFixture.java
  backend/src/test/java/com/now/naaga/game/fixture/PlaceFixture.java
  backend/src/test/java/com/now/naaga/game/fixture/PlayerFixture.java
  backend/src/test/java/com/now/naaga/game/fixture/PositionFixture.java
  backend/src/test/java/com/now/naaga/game/presentation/GameControllerTest.java
  backend/src/test/java/com/now/naaga/game/presentation/StatisticControllerTest.java
  backend/src/test/java/com/now/naaga/place/fixture/PlaceFixture.java
  backend/src/test/java/com/now/naaga/place/fixture/PositionFixture.java
  backend/src/test/java/com/now/naaga/place/presentation/PlaceControllerTest.java
  backend/src/test/java/com/now/naaga/player/fixture/PlayerFixture.java
  backend/src/test/java/com/now/naaga/player/persistence/repository/PlayerRepositoryTest.java
  backend/src/test/java/com/now/naaga/player/presentation/PlayerControllerTest.java
  backend/src/test/java/com/now/naaga/score/fixture/ScoreFixture.java
Labels: 🍀 백엔드, 4차 데모데이

#290 [AN] feat: 버전 변경
  android/app/build.gradle
Labels: 🦄 안드로이드, 4차 데모데이
