Repository woowacourse-teams/2023-naaga, pull requests merged in 2023-07, with the labels that each got.

#3 [AN] 프로젝트 폴더 생성
  android/.gitkeep.txt
Labels: 🤖 안드로이드

#5 [AN] feat: 안드로이드 프로젝트 초기 세팅
  android/.gitignore
  android/.idea/.gitignore
  android/.idea/.name
  android/.idea/compiler.xml
  android/.idea/gradle.xml
  android/.idea/misc.xml
  android/.idea/vcs.xml
  android/app/.gitignore
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/now/naaga/ExampleInstrumentedTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/MainActivity.kt
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-anydpi-v33/ic_launcher.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/main/res/xml/backup_rules.xml
  android/app/src/main/res/xml/data_extraction_rules.xml
  android/app/src/test/java/com/now/naaga/ExampleUnitTest.kt
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
Labels: 🤖 안드로이드, 2차 데모데이

#7 [BE] feat: 프로젝트 초기 세팅
  .DS_Store
  backend/.DS_Store
  backend/HELP.md
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/now/naaga/NaagaApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/now/naaga/NaagaApplicationTests.java
Labels: 🍀 백엔드, 2차 데모데이

#12 [AN] chore: 패키지 구조 설정
  android/.idea/gradle.xml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/mapper/.gitkeep
  android/app/src/main/java/com/now/naaga/data/remote/dto/.gitkeep
  android/app/src/main/java/com/now/naaga/data/repository/.gitkeep
  android/app/src/main/java/com/now/naaga/presentation/MainActivity.kt
  android/app/src/main/res/layout/activity_main.xml
  android/build.gradle
  android/domain/.gitignore
  android/domain/build.gradle
  android/settings.gradle
Labels: 🤖 안드로이드, 2차 데모데이

#16 [AN] feat: 초기 resource 파일 세팅
  android/app/src/main/res/drawable/ic_logo_white.xml
  android/app/src/main/res/drawable/ic_photo.xml
  android/app/src/main/res/drawable/rectangle_main_gradient.xml
  android/app/src/main/res/font/pretendard_bold.otf
  android/app/src/main/res/font/pretendard_medium.otf
  android/app/src/main/res/font/pretendard_semibold.otf
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
Labels: 🤖 안드로이드, 2차 데모데이

#18 [AN] feat: DTO 생성
  android/app/src/main/java/com/now/naaga/data/remote/dto/.gitkeep
  android/app/src/main/java/com/now/naaga/data/remote/dto/DestinationDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/PositionDto.kt
Labels: 🤖 안드로이드, 2차 데모데이

#23 [AN] feat: 네이버 맵을 화면에 띄우는 기능 구현
  android/.gitignore
  android/.idea/.gitignore
  android/.idea/.name
  android/.idea/compiler.xml
  android/.idea/gradle.xml
  android/.idea/misc.xml
  android/.idea/vcs.xml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/presentation/MainActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/gradle.properties
  android/settings.gradle
Labels: 🤖 안드로이드, 2차 데모데이

#26 [BE] feat: 회원 인증 기능 구현
  backend/src/main/java/com/now/naaga/auth/annotation/Auth.java
  backend/src/main/java/com/now/naaga/auth/application/AuthService.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/AuthenticationExtractor.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/BasicAuthenticationDecoder.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/BasicAuthenticationExtractor.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthInterceptor.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthenticationArgumentResolver.java
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/member/dto/MemberCommand.java
  backend/src/main/java/com/now/naaga/member/persistence/repository/MemberRepository.java
  backend/src/main/java/com/now/naaga/member/service/MemberService.java
  backend/src/test/java/com/now/naaga/config/infrastructure/BasicAuthenticationDecoderTest.java
  backend/src/test/java/com/now/naaga/member/persistence/repository/MemberRepositoryTest.java
Labels: 🍀 백엔드, 2차 데모데이

#29 [BE] feat: 장소 추천 기능 구현
  backend/src/main/java/com/now/naaga/NaagaApplication.java
  backend/src/main/java/com/now/naaga/auth/application/AuthService.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthenticationArgumentResolver.java
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/domain/Game.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/PlaceResponse.java
  backend/src/main/java/com/now/naaga/game/repository/GameRepository.java
  backend/src/main/java/com/now/naaga/member/application/MemberService.java
  backend/src/main/java/com/now/naaga/member/persistence/repository/MemberRepository.java
  backend/src/main/java/com/now/naaga/place/application/PlaceService.java
  backend/src/main/java/com/now/naaga/place/persistence/repository/PlaceRepository.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
Labels: 🍀 백엔드, 2차 데모데이

#35 [AN] feat: 목적지와 현재위치 사이 거리를 계산하여 사용자에게 보여주는 기능 구현
  android/app/src/main/java/com/now/naaga/data/repository/.gitkeep
  android/app/src/main/java/com/now/naaga/data/repository/MockDestinationRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/model/Destination.kt
  android/domain/src/main/java/com/now/domain/repository/DestinationRepository.kt
Labels: 🤖 안드로이드, 2차 데모데이

#39 [AN] feat: 목적지를 마커로 표시하는 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
Labels: 🤖 안드로이드, 2차 데모데이

#40 [AN] feat: 사진 버튼을 클릭하면 사진 다이얼로그를 띄우는 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/LocationPermissionDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/PolaroidDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/util/DisplayUtil.kt
  android/app/src/main/res/drawable/ic_close.xml
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/layout/dialog_polaroid.xml
  android/app/src/main/res/values/strings.xml
Labels: 🤖 안드로이드, 2차 데모데이

#41 [AN] feat: 목적지에 도착 시 도착 버튼 활성화 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/res/color/selector_main_gray_purple.xml
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/values/colors.xml
Labels: 🤖 안드로이드, 2차 데모데이

#43 [BE] refactor: API 명세 변경으로 인한 기능 수정
  backend/src/main/java/com/now/naaga/auth/application/AuthService.java
  backend/src/main/java/com/now/naaga/auth/exception/AuthException.java
  backend/src/main/java/com/now/naaga/auth/exception/AuthExceptionType.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/BasicAuthenticationExtractor.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthInterceptor.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthenticationArgumentResolver.java
  backend/src/main/java/com/now/naaga/common/exception/BaseException.java
  backend/src/main/java/com/now/naaga/common/exception/BaseExceptionType.java
  backend/src/main/java/com/now/naaga/common/exception/ControllerExceptionHandler.java
  backend/src/main/java/com/now/naaga/common/exception/ExceptionResponse.java
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/domain/Game.java
  backend/src/main/java/com/now/naaga/game/domain/GameStatus.java
  backend/src/main/java/com/now/naaga/game/exception/GameException.java
  backend/src/main/java/com/now/naaga/game/exception/GameExceptionType.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameResponse.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameStatusResponse.java
  backend/src/main/java/com/now/naaga/game/repository/GameRepository.java
  backend/src/main/java/com/now/naaga/member/application/MemberService.java
  backend/src/main/java/com/now/naaga/member/application/dto/MemberCommand.java
  backend/src/main/java/com/now/naaga/member/exception/MemberException.java
  backend/src/main/java/com/now/naaga/member/exception/MemberExceptionType.java
  backend/src/main/java/com/now/naaga/place/application/PlaceService.java
  backend/src/main/java/com/now/naaga/place/exception/PlaceException.java
  backend/src/main/java/com/now/naaga/place/exception/PlaceExceptionType.java
  backend/src/main/java/com/now/naaga/place/presentation/dto/PlaceResponse.java
Labels: 🍀 백엔드, 2차 데모데이

#44 [AN] feat: 서버통신 초기세팅
  android/app/src/main/java/com/now/naaga/data/mapper/.gitkeep
  android/app/src/main/java/com/now/naaga/data/mapper/AdventureMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/CoordinateMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/DestinationMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitFactory.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt
  android/app/src/main/java/com/now/naaga/data/repository/MockAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/MockDestinationRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/PolaroidDialog.kt
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/model/Adventure.kt
  android/domain/src/main/java/com/now/domain/model/AdventureStatus.kt
  android/domain/src/main/java/com/now/domain/model/Destination.kt
  android/domain/src/main/java/com/now/domain/repository/AdventureRepository.kt
  android/domain/src/main/java/com/now/domain/repository/DestinationRepository.kt
Labels: 🦄 안드로이드, 2차 데모데이

#47 [BE] feat: 목적지 도착 여부 확인 기능 구현
  backend/src/main/java/com/now/naaga/auth/application/AuthService.java
  backend/src/main/java/com/now/naaga/auth/exception/AuthExceptionType.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/AuthenticationExtractor.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/BasicAuthenticationDecoder.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/BasicAuthenticationExtractor.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthInterceptor.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthenticationArgumentResolver.java
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/domain/Game.java
  backend/src/main/java/com/now/naaga/game/domain/GameStatus.java
  backend/src/main/java/com/now/naaga/game/exception/GameExceptionType.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameResponse.java
  backend/src/main/java/com/now/naaga/game/presentation/dto/GameStatusResponse.java
  backend/src/main/java/com/now/naaga/game/repository/GameRepository.java
  backend/src/main/java/com/now/naaga/member/application/MemberService.java
  backend/src/main/java/com/now/naaga/member/application/dto/MemberCommand.java
  backend/src/main/java/com/now/naaga/member/domain/Member.java
  backend/src/main/java/com/now/naaga/member/exception/MemberExceptionType.java
  backend/src/main/java/com/now/naaga/member/persistence/repository/MemberRepository.java
  backend/src/main/java/com/now/naaga/place/application/PlaceService.java
  backend/src/main/java/com/now/naaga/place/domain/Place.java
  backend/src/main/java/com/now/naaga/place/domain/Position.java
  backend/src/main/java/com/now/naaga/place/exception/PlaceExceptionType.java
  backend/src/main/java/com/now/naaga/place/persistence/repository/PlaceRepository.java
  backend/src/main/java/com/now/naaga/place/presentation/dto/PlaceResponse.java
Labels: 🍀 백엔드, 2차 데모데이

#50 [BE] feat: 백엔드 ci workflows 초안 작성
  .github/workflows/backend_dev_ci_workflow.yml
Labels: 🍀 백엔드, 2차 데모데이

#51 [BE] fix: 백엔드 ci workflows 초안 작성
  .github/workflows/backend_dev_ci_workflow.yml
Labels: 🍀 백엔드, 2차 데모데이

#52 [BE] fix: working directory 상대경로로 변경
  .github/workflows/backend_dev_ci_workflow.yml
Labels: 🍀 백엔드, 2차 데모데이

#48 [AN] feat: 서버에 모험 시작을 요청하는 기능 구현
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/NaagaThrowable.kt
  android/app/src/main/java/com/now/naaga/data/mapper/CoordinateMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/FailureDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitFactory.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitUtil.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/MockAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/domain/src/main/java/com/now/domain/repository/AdventureRepository.kt
Labels: 🦄 안드로이드, 2차 데모데이

#53 [AN] feat: 모험이 끝났을 때 서버에게 모험이 종료 됐음을 알려주는 기능 구현
  android/app/src/main/java/com/now/naaga/data/mapper/AdventureMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/EndedAdventureDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/MockAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/repository/AdventureRepository.kt
Labels: 🦄 안드로이드, 2차 데모데이

#54 [AN] feat: 서버에서 목적지를 받아오는 기능 구현
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
Labels: 🦄 안드로이드, 2차 데모데이

#56 [AN] fix: 목적지 도착 버튼 클릭 시 발생하는 오류 수정
  android/app/src/main/java/com/now/naaga/data/remote/dto/EndedAdventureDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
Labels: 🦄 안드로이드, 2차 데모데이

#75 [AN] feat: 안드로이드 프로젝트에 firebase 추가
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
Labels: 🦄 안드로이드, 2차 데모데이

#77 [AN] feat: 안드로이드 CI 자동화
  .github/workflows/android_ci.yml
  android/.editorconfig
  android/app/src/androidTest/java/com/now/naaga/ExampleInstrumentedTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/NaagaThrowable.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_close.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/ic_location.xml
  android/app/src/main/res/drawable/ic_logo_white.xml
  android/app/src/main/res/drawable/ic_photo.xml
  android/app/src/main/res/drawable/rect_radius_large.xml
  android/app/src/main/res/drawable/rect_radius_small.xml
  android/app/src/main/res/drawable/rectangle_main_gradient.xml
  android/app/src/main/res/layout/activity_begin_adventure.xml
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/layout/dialog_location_permission.xml
  android/app/src/main/res/layout/dialog_polaroid.xml
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/test/java/com/now/naaga/ExampleUnitTest.kt
Labels: 🦄 안드로이드, 2차 데모데이

#58 [AN] feat: 스플래시 화면에서 진행 중인 모험이 있는지 판단하고 분기 하는 기능 구현
  android/.editorconfig
  android/.gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/MockAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModelFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/AdventureMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/CoordinateMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/DestinationMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/AdventureUiModel.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/CoordinateUiModel.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/DestinationUiModel.kt
  android/app/src/main/java/com/now/naaga/util/IntentExt.kt
  android/app/src/main/res/drawable/ic_logo_splash.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/values/themes.xml
  android/domain/src/main/java/com/now/domain/repository/AdventureRepository.kt
Labels: 🦄 안드로이드, 2차 데모데이

#72 [AN] feat: registerForActivityResult 분기처리 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/LocationPermissionDialog.kt
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 3차 데모데이

#71 [AN] feat: BeginAdeventureActivity UI 변경사항 적용
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/res/drawable/ic_mypage.xml
  android/app/src/main/res/drawable/ic_rank.xml
  android/app/src/main/res/drawable/ic_upload.xml
  android/app/src/main/res/drawable/rect_radius_small_white.xml
  android/app/src/main/res/layout/activity_begin_adventure.xml
  android/app/src/main/res/values/styles.xml
Labels: 🦄 안드로이드, 3차 데모데이

#80 [AN] feat: AdventureResultActivity 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/res/drawable/ic_fail.xml
  android/app/src/main/res/drawable/ic_success.xml
  android/app/src/main/res/layout/activity_adventure_result.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 3차 데모데이

#84 [BE] feat: 3차 데모데이 엔티티 설계
  backend/src/main/java/com/now/naaga/NaagaApplication.java
  backend/src/main/java/com/now/naaga/auth/application/AuthService.java
  backend/src/main/java/com/now/naaga/auth/infrastructure/BasicAuthenticationExtractor.java
  backend/src/main/java/com/now/naaga/auth/presentation/AuthenticationArgumentResolver.java
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/common/domain/BaseEntity.java
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/domain/Direction.java
  backend/src/main/java/com/now/naaga/game/domain/Game.java
  backend/src/main/java/com/now/naaga/game/domain/GameResult.java
  backend/src/main/java/com/now/naaga/game/domain/Hint.java
  backend/src/main/java/com/now/naaga/game/domain/ResultType.java
  backend/src/main/java/com/now/naaga/game/presentation/GameController.java
  backend/src/main/java/com/now/naaga/game/repository/GameRepository.java
  backend/src/main/java/com/now/naaga/game/repository/GameResultRepository.java
  backend/src/main/java/com/now/naaga/game/repository/HintRepository.java
  backend/src/main/java/com/now/naaga/member/application/MemberService.java
  backend/src/main/java/com/now/naaga/member/domain/Member.java
  backend/src/main/java/com/now/naaga/member/persistence/repository/MemberRepository.java
  backend/src/main/java/com/now/naaga/place/application/PlaceService.java
  backend/src/main/java/com/now/naaga/place/domain/Place.java
  backend/src/main/java/com/now/naaga/place/domain/Position.java
  backend/src/main/java/com/now/naaga/place/persistence/repository/PlaceRepository.java
  backend/src/main/java/com/now/naaga/player/domain/Player.java
  backend/src/main/java/com/now/naaga/player/persistence/repository/PlayerRepository.java
  backend/src/main/java/com/now/naaga/score/domain/Score.java
Labels: 🍀 백엔드, 3차 데모데이

#73 [AN] feat: OnAdventureActivity UI 변경사항 적용
  android/app/.gitignore
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/res/drawable/ic_drop.xml
  android/app/src/main/res/drawable/ic_hint.xml
  android/app/src/main/res/drawable/oval_radius_midium.xml
  android/app/src/main/res/drawable/rect_main_gradient.xml
  android/app/src/main/res/drawable/rect_white_radius_small.xml
  android/app/src/main/res/drawable/rectangle_main_gradient.xml
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/values/themes.xml
Labels: 🦄 안드로이드, 3차 데모데이

#79 [AN] feat: UploadActivity 구현
  android/.gitignore
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/res/drawable/ic_camera.xml
  android/app/src/main/res/drawable/ic_coordinate.xml
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/layout/activity_upload.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 3차 데모데이

#89 feat: 명세서 기준으로 Dto들 생성
  android/app/src/main/java/com/now/naaga/data/remote/dto/second/AdventureResultDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/second/AdventureStatusDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/second/FinishGameDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/second/GameDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/second/HintDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/second/PlaceDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/second/PlayerDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/second/RankDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/second/StatisticDto.kt
Labels: 🦄 안드로이드, 3차 데모데이

#93 [AN] feat: 디바이스의 위치를 받아와 뷰에 보여주는 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
Labels: 🦄 안드로이드, 3차 데모데이

#91 [AN] feat: 도메인 모델 생성
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/AdventureResultDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/AdventureStatusDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/FinishGameDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/GameDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/HintDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/PlaceDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/PlayerDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/RankDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/StatisticDto.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
  android/domain/src/main/java/com/now/domain/model/AdventureEndType.kt
  android/domain/src/main/java/com/now/domain/model/AdventureResult.kt
  android/domain/src/main/java/com/now/domain/model/AdventureResultType.kt
  android/domain/src/main/java/com/now/domain/model/AdventureStatus.kt
  android/domain/src/main/java/com/now/domain/model/Direction.kt
  android/domain/src/main/java/com/now/domain/model/Game.kt
  android/domain/src/main/java/com/now/domain/model/Hint.kt
  android/domain/src/main/java/com/now/domain/model/Place.kt
  android/domain/src/main/java/com/now/domain/model/Player.kt
  android/domain/src/main/java/com/now/domain/model/Rank.kt
  android/domain/src/main/java/com/now/domain/model/RemainingTryCount.kt
  android/domain/src/main/java/com/now/domain/model/Statistic.kt
Labels: 🦄 안드로이드, 3차 데모데이

#101 [AN] feat: 통계 path 레트로핏 서비스 구현
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/StatisticsService.kt
Labels: 🦄 안드로이드, 3차 데모데이

#102 [AN] feat: 게임 path 레트로핏 서비스 구현
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/Adventure2Service.kt
Labels: 🦄 안드로이드, 3차 데모데이

#103 feat: 장소 path 레트로핏 서비스 구현
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
Labels: 🦄 안드로이드, 3차 데모데이

#106 [AN] feat: AdventureHistoryActivity 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryViewHolder.kt
  android/app/src/main/res/drawable/ic_arrow.xml
  android/app/src/main/res/layout/activity_adventure_history.xml
  android/app/src/main/res/layout/item_history.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 3차 데모데이

#109 [AN] feat: RankRepository 생성
  android/app/src/main/java/com/now/naaga/data/mapper/PlayerMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/RankMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/RankService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultRankRepository.kt
  android/domain/src/main/java/com/now/domain/repository/RankRepository.kt
Labels: 🦄 안드로이드, 3차 데모데이

#110 [AN] feat: StatisticsRepository 생성
  android/app/src/main/java/com/now/naaga/data/mapper/StatisticsMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/third/StatisticsDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/StatisticsService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultStatisticsRepository.kt
  android/domain/src/main/java/com/now/domain/model/Statistics.kt
  android/domain/src/main/java/com/now/domain/repository/StatisticsRepository.kt
Labels: 🦄 안드로이드, 3차 데모데이

#111 feat: 3차 데모데이 기획 변경에 맞는 AdventureRepository 설계 및 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/mapper/AdventureMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/AdventureResultMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/HintMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/PlaceMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitUtil.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/ThirdDemoAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryViewHolder.kt
  android/domain/src/main/java/com/now/domain/model/AdventureResultType.kt
  android/domain/src/main/java/com/now/domain/model/OrderType.kt
  android/domain/src/main/java/com/now/domain/model/SortType.kt
  android/domain/src/main/java/com/now/domain/repository/AdventureRepository2.kt
Labels: 🦄 안드로이드, 3차 데모데이

#118 [AN] feat: PlaceRepository 생성
  android/app/src/main/java/com/now/naaga/data/mapper/PlaceMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
  android/domain/src/main/java/com/now/domain/repository/PlaceRepository.kt
Labels: 🦄 안드로이드, 3차 데모데이
