Repository woowacourse-teams/2023-naaga, pull requests merged in 2023-10, with the labels that each got.

#378 refactor: 디자인 수정을 위한 공통 요소 추가
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryViewHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/res/drawable/ic_all_adventure.xml
  android/app/src/main/res/drawable/ic_camera_dialog.xml
  android/app/src/main/res/drawable/ic_fail_adventure.xml
  android/app/src/main/res/drawable/ic_fail_lable.xml
  android/app/src/main/res/drawable/ic_flag.xml
  android/app/src/main/res/drawable/ic_hint.xml
  android/app/src/main/res/drawable/ic_location_dialog.xml
  android/app/src/main/res/drawable/ic_marker_east.xml
  android/app/src/main/res/drawable/ic_marker_north.xml
  android/app/src/main/res/drawable/ic_marker_south.xml
  android/app/src/main/res/drawable/ic_marker_west.xml
  android/app/src/main/res/drawable/ic_message_received.xml
  android/app/src/main/res/drawable/ic_message_send.xml
  android/app/src/main/res/drawable/ic_mypage.xml
  android/app/src/main/res/drawable/ic_success_adventure.xml
  android/app/src/main/res/drawable/ic_success_lable.xml
  android/app/src/main/res/drawable/rect_main_gradient.xml
  android/app/src/main/res/font/main_font.otf
  android/app/src/main/res/layout/activity_adventure_result.xml
  android/app/src/main/res/layout/activity_begin_adventure.xml
  android/app/src/main/res/layout/activity_rank.xml
  android/app/src/main/res/layout/item_history.xml
  android/app/src/main/res/layout/skeleton_begin_adventure.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/themes.xml
Labels: D-0, 뽀또🍪, 빅스💻, 6차 데모데이

#373 feat: 장소 검수 기능 뼈대코드 설계 및 구현
  backend/src/main/java/com/now/naaga/temporaryplace/domain/TemporaryPlace.java
  backend/src/main/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceController.java
  backend/src/main/java/com/now/naaga/temporaryplace/repository/TemporaryPlaceRepository.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#344 feat: 장소 좋아요 기능 도메인 설계 및 뼈대코드 작성
  backend/src/main/java/com/now/naaga/like/domain/PlaceLike.java
  backend/src/main/java/com/now/naaga/like/domain/PlaceLikeType.java
  backend/src/main/java/com/now/naaga/like/repository/PlaceLikeRepository.java
  backend/src/main/java/com/now/naaga/placestatistics/PlaceStatistics.java
  backend/src/main/java/com/now/naaga/placestatistics/repository/PlaceStatisticsRepository.java
  backend/src/test/java/com/now/naaga/common/builder/PlaceLikeBuilder.java
  backend/src/test/java/com/now/naaga/common/builder/PlaceStatisticsBuilder.java
  backend/src/test/java/com/now/naaga/common/fixture/PlaceLikeFixture.java
  backend/src/test/java/com/now/naaga/common/fixture/PlaceStatisticsFixture.java
Labels: 🍀 백엔드, 5차 데모데이, D-0

#375 fix: OkHttpClient의 interceptor를 AuthInterceptor로 변경
  android/app/src/main/java/com/now/naaga/di/ServiceModule.kt
Labels: 🦄 안드로이드, D-2, 뽀또🍪, 6차 데모데이

#374 feat: 장소 등록 검수 관리자 페이지 제작 및 인가 인터셉터 추가
  backend/src/main/java/com/now/naaga/auth/exception/AuthExceptionType.java
  backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcher.java
  backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptor.java
  backend/src/main/java/com/now/naaga/common/presentation/interceptor/RequestPattern.java
  backend/src/test/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptorTest.java
  backend/src/test/java/com/now/naaga/common/presentation/interceptor/RequestMatcherInterceptorTest.java
  backend/src/test/java/com/now/naaga/common/presentation/interceptor/RequestPatternTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#364 fix: 나의 통계 조회 시 성능 저하 문제 해결
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/gameresult/domain/GameResult.java
  backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
  backend/src/main/java/com/now/naaga/place/domain/Place.java
  backend/src/test/java/com/now/naaga/gameresult/application/GameResultServiceTest.java
  backend/src/test/java/com/now/naaga/gameresult/repository/GameResultRepositoryTest.java
Labels: 🍀 백엔드, 5차 데모데이, D-0

#383 fix: 모든 게임 결과 조회 시, 진행중 게임 있으면 예외 발생하는 사항 수정
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/gameresult/repository/GameResultRepository.java
  backend/src/test/java/com/now/naaga/game/application/GameServiceTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#396 Refactor/#391 모험 기록 뷰 디자인 변경
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryViewHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/res/drawable/ic_fail_label.xml
  android/app/src/main/res/drawable/ic_success_label.xml
  android/app/src/main/res/drawable/ic_success_lable.xml
  android/app/src/main/res/layout/activity_adventure_history.xml
  android/app/src/main/res/layout/item_history.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, D-2, 크롱🦖, 6차 데모데이

#400 feat: 앱 강제 업데이트 기능 구현
  android/app/build.gradle
  android/app/src/main/java/com/now/naaga/common/dialog/ConfirmDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/util/extension/IntentExt.kt
  android/app/src/main/java/com/now/naaga/util/extension/PackageManagerExt.kt
  android/app/src/main/res/layout/dialog_confirm.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, D-2, 뽀또🍪, 6차 데모데이

#399 refactor: 로그인 뷰 디자인 변경
  android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
  android/app/src/main/res/drawable/ic_building_full.xml
  android/app/src/main/res/drawable/ic_star.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, D-2, 크롱🦖, 6차 데모데이

#381 refactor: 업로드 뷰 디자인 변경
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
  android/app/src/main/res/drawable/bg_button.xml
  android/app/src/main/res/layout/activity_upload.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/test/java/com/now/naaga/UploadViewModelTestWithRobolectric.kt
Labels: 🦄 안드로이드, D-2, 뽀또🍪, 6차 데모데이

#397 refactor: 설정 뷰 디자인 변경
  android/app/src/main/res/drawable/ic_building.xml
  android/app/src/main/res/drawable/ic_star.xml
  android/app/src/main/res/layout/activity_setting.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, D-2, 크롱🦖, 빅스💻, 6차 데모데이

#395 refactor: my page 뷰 디자인 변경
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageCustomGrid.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageItemUiModel.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/place/MyPageCustomGrid.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/place/MyPagePlaceAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/place/MyPagePlaceViewHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/statistics/MyPageStatisticsAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/statistics/MyPageStatisticsViewHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/MyPagePlaceUiModel.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/StatisticsUiModel.kt
  android/app/src/main/res/drawable/ic_all_adventure.xml
  android/app/src/main/res/drawable/ic_fail_adventure.xml
  android/app/src/main/res/drawable/oval_blue_gradient.xml
  android/app/src/main/res/drawable/oval_orange_gradient.xml
  android/app/src/main/res/drawable/oval_yellow_gradient.xml
  android/app/src/main/res/drawable/rect_radius_small_white.xml
  android/app/src/main/res/layout/activity_my_page.xml
  android/app/src/main/res/layout/custom_mypage_grid.xml
  android/app/src/main/res/layout/custom_mypage_grid_empty.xml
  android/app/src/main/res/layout/item_history.xml
  android/app/src/main/res/layout/item_rank.xml
  android/app/src/main/res/layout/rv_mypage_item_adventure.xml
  android/app/src/main/res/layout/rv_mypage_item_place.xml
  android/app/src/main/res/layout/rv_mypage_item_statistics.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, D-2, 빅스💻, 6차 데모데이

#411 fix: 장소 추천 범위 정상화
  backend/src/main/java/com/now/naaga/place/domain/PlaceRecommendService.java
  backend/src/test/java/com/now/naaga/place/service/PlaceServiceTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#408 refactor: 게임 시작 뷰 디자인 변경
  android/app/src/main/java/com/now/naaga/data/firebase/analytics/ButtonNames.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/res/drawable/bg_blue_button.xml
  android/app/src/main/res/drawable/bg_button.xml
  android/app/src/main/res/drawable/bg_yellow_button.xml
  android/app/src/main/res/layout/activity_adventure_result.xml
  android/app/src/main/res/layout/activity_begin_adventure.xml
  android/app/src/main/res/layout/activity_upload.xml
  android/app/src/main/res/layout/dialog_location_permission.xml
  android/app/src/main/res/layout/skeleton_begin_adventure.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: 🦄 안드로이드, D-1, 크롱🦖, 6차 데모데이

#413 feat: 업로드 화면에서 뒤로가기 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 빅스💻, 6차 데모데이

#407 feat: 게임 입장 시 사진이 먼저 뜨는 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 빅스💻, 6차 데모데이

#398 feat: 검수 중인 장소에 대한 장소 등록 허가 API 구현
  backend/src/main/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptor.java
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/place/application/PlaceService.java
  backend/src/main/java/com/now/naaga/place/application/dto/CreatePlaceCommand.java
  backend/src/main/java/com/now/naaga/place/presentation/PlaceController.java
  backend/src/main/java/com/now/naaga/place/presentation/dto/CreatePlaceRequest.java
  backend/src/main/java/com/now/naaga/place/presentation/dto/PlaceResponse.java
  backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
  backend/src/test/java/com/now/naaga/auth/presentation/interceptor/ManagerAuthInterceptorTest.java
  backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
  backend/src/test/java/com/now/naaga/place/presentation/PlaceControllerTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#401 feat: 검수 중인 장소에 대한 등록 승인 거절 API 구현
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/place/presentation/PlaceController.java
  backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
  backend/src/main/java/com/now/naaga/temporaryplace/domain/TemporaryPlace.java
  backend/src/main/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceController.java
  backend/src/test/java/com/now/naaga/common/builder/TemporaryPlaceBuilder.java
  backend/src/test/java/com/now/naaga/place/application/PlaceServiceTest.java
  backend/src/test/java/com/now/naaga/temporaryplace/application/TemporaryPlaceServiceTest.java
  backend/src/test/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceControllerTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#404 feat: 검수할 장소 등록/ 조회 API 구현
  .idea/2023-naaga.iml
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/place/domain/PlaceCheckService.java
  backend/src/main/java/com/now/naaga/place/presentation/PlaceController.java
  backend/src/main/java/com/now/naaga/temporaryplace/application/TemporaryPlaceService.java
  backend/src/main/java/com/now/naaga/temporaryplace/application/dto/CreateTemporaryPlaceCommand.java
  backend/src/main/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceController.java
  backend/src/main/java/com/now/naaga/temporaryplace/presentation/dto/CreateTemporaryPlaceRequest.java
  backend/src/main/java/com/now/naaga/temporaryplace/presentation/dto/TemporaryPlaceResponse.java
  backend/src/main/java/com/now/naaga/temporaryplace/repository/TemporaryPlaceRepository.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/now/naaga/common/fixture/TemporaryPlaceFixture.java
  backend/src/test/java/com/now/naaga/temporaryplace/fixture/루터회관.png
  backend/src/test/java/com/now/naaga/temporaryplace/presentation/TemporaryPlaceControllerTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#417 refactor: 버튼 디자인 일관성 있도록 변경
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/res/layout/activity_adventure_history.xml
  android/app/src/main/res/layout/activity_adventure_result.xml
  android/app/src/main/res/layout/activity_my_page.xml
  android/app/src/main/res/layout/activity_upload.xml
  android/app/src/main/res/layout/dialog_camera_permission.xml
Labels: 🦄 안드로이드, D-1, 크롱🦖, 빅스💻, 6차 데모데이

#418 refactor: 인게임 뷰 디자인 변경
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/res/drawable/ic_compass.xml
  android/app/src/main/res/drawable/ic_drop.xml
  android/app/src/main/res/drawable/ic_hint.xml
  android/app/src/main/res/drawable/ic_stop.xml
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/layout/dialog_naaga_alert.xml
  android/app/src/main/res/layout/dialog_polaroid.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 6차 데모데이

#421 refactor: NaagaAlertDialog와 ConfirmDialog 통일
  android/app/src/main/java/com/now/naaga/common/dialog/ConfirmDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/CameraPermissionDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/LocationPermissionDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/NaagaAlertDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/PolaroidDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/res/layout/dialog_confirm.xml
Labels: 🦄 안드로이드, D-0, 크롱🦖, 6차 데모데이

#369 refactor: 장소 등록 api 수정
  android/app/src/main/java/com/now/naaga/data/mapper/PlaceMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/PostPlaceDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 빅스💻, 6차 데모데이

#424 refactor: 인게임 버튼 drawable resource 변경
  android/app/src/main/res/drawable/bg_yellow_button_thick.xml
  android/app/src/main/res/layout/activity_on_adventure.xml
Labels: 🦄 안드로이드, 뽀또🍪, 6차 데모데이

#426 refactor: permission dialog 통일
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/CameraPermissionDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/DialogType.kt
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/PermissionDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/res/layout/dialog_camera_permission.xml
  android/app/src/main/res/layout/dialog_permission.xml
  android/app/src/main/res/values/strings.xml
  android/naaga
Labels: 🦄 안드로이드, 빅스💻, 6차 데모데이

#427 feat: 문의하기 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, D-0, 크롱🦖, 빅스💻, 6차 데모데이

#431 feat: 버전코드 및 버전이름 수정
  android/app/build.gradle
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 6차 데모데이

#389 feat: 쪽지 기능 뼈대코드 설계 및 구현
  backend/src/main/java/com/now/naaga/letter/domain/Letter.java
  backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
  backend/src/main/java/com/now/naaga/letter/repository/LetterRepository.java
  backend/src/test/java/com/now/naaga/common/builder/LetterBuilder.java
  backend/src/test/java/com/now/naaga/common/fixture/LetterFixture.java
  backend/src/test/java/com/now/naaga/common/fixture/PositionFixture.java
Labels: 🍀 백엔드, 6차 데모데이

#435 hotfix: 액세스 토큰 리프레시 및 자동 로그인 로직 수정
  android/app/build.gradle
  android/app/src/main/java/com/now/naaga/data/local/DefaultAuthDataSource.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 빅스💻, 6차 데모데이

#446 hotfix: 액세스 토큰 리프레시 로직 수정
  android/app/build.gradle
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 빅스💻, 6차 데모데이

#447 hotfix: 액세스 토큰 리프레시 로직 수정
  android/app/build.gradle
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 6차 데모데이

#440 refactor: RetrofitFactory 삭제
  android/app/src/main/java/com/now/naaga/data/firebase/analytics/ButtonNames.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/AdventureDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/RefreshTokenDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitFactory.kt
Labels: 🦄 안드로이드, D-2, 크롱🦖, 6차 데모데이

#450 feat: 쪽지 관련 공통 코드 작성
  android/app/src/main/java/com/now/naaga/data/mapper/AdventureResultMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/AuthMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/PlaceMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/ClosedLetterDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/OpenLetterDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/post/PostLetterDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/post/PostPlaceDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/LetterService.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultLetterRepository.kt
  android/app/src/main/java/com/now/naaga/di/RepositoryModule.kt
  android/app/src/main/java/com/now/naaga/di/ServiceModule.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryViewHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
  android/app/src/test/java/com/now/naaga/AdventureHistoryViewModelTest.kt
  android/app/src/test/java/com/now/naaga/AdventureResultViewModelTest.kt
  android/app/src/test/java/com/now/naaga/RankViewModelTest.kt
  android/domain/src/main/java/com/now/domain/model/AdventureResult.kt
  android/domain/src/main/java/com/now/domain/model/Place.kt
  android/domain/src/main/java/com/now/domain/model/PlatformAuth.kt
  android/domain/src/main/java/com/now/domain/model/RestTryCount.kt
  android/domain/src/main/java/com/now/domain/model/letter/ClosedLetter.kt
  android/domain/src/main/java/com/now/domain/model/letter/OpenLetter.kt
  android/domain/src/main/java/com/now/domain/model/type/AdventureEndType.kt
  android/domain/src/main/java/com/now/domain/model/type/AdventureResultType.kt
  android/domain/src/main/java/com/now/domain/model/type/AuthPlatformType.kt
  android/domain/src/main/java/com/now/domain/model/type/LogType.kt
  android/domain/src/main/java/com/now/domain/model/type/OrderType.kt
  android/domain/src/main/java/com/now/domain/model/type/SortType.kt
  android/domain/src/main/java/com/now/domain/repository/AdventureRepository.kt
  android/domain/src/main/java/com/now/domain/repository/LetterRepository.kt
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 6차 데모데이

#453 feat: 쪽지 전송 다이얼로그 구현
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/LetterSendDialog.kt
  android/app/src/main/res/drawable/rect_red_white_radius_small.xml
  android/app/src/main/res/layout/dialog_send_letter.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 6차 데모데이

#441 feat: 쪽지 기록 기능 뼈대코드 설계 및 구현
  backend/src/main/java/com/now/naaga/letter/domain/Letter.java
  backend/src/main/java/com/now/naaga/letter/domain/letterlog/ReadLetterLog.java
  backend/src/main/java/com/now/naaga/letter/domain/letterlog/WriteLetterLog.java
  backend/src/main/java/com/now/naaga/letter/presentation/LetterLogController.java
  backend/src/main/java/com/now/naaga/letter/repository/letterlog/ReadLetterLogRepository.java
  backend/src/main/java/com/now/naaga/letter/repository/letterlog/WriteLetterLogRepository.java
  backend/src/test/java/com/now/naaga/common/builder/ReadLetterLogBuilder.java
  backend/src/test/java/com/now/naaga/common/builder/WriteLetterLogBuilder.java
  backend/src/test/java/com/now/naaga/common/fixture/GameFixture.java
  backend/src/test/java/com/now/naaga/common/fixture/ReadLetterLogFixture.java
  backend/src/test/java/com/now/naaga/common/fixture/WriteLetterLogFixture.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#458 fix: 저장소 권한 요청 및 알림 변경
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultRankRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultStatisticsRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/PermissionDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
  android/app/src/main/java/com/now/naaga/util/extension/ContextExt.kt
  android/app/src/main/java/com/now/naaga/util/extension/ResponseExt.kt
  android/app/src/main/java/com/now/naaga/util/extension/ViewExt.kt
  android/app/src/main/java/com/now/naaga/util/singleliveevent/Event.kt
  android/app/src/main/java/com/now/naaga/util/singleliveevent/MutableSingleLiveData.kt
  android/app/src/main/java/com/now/naaga/util/singleliveevent/SingleLiveData.kt
  android/app/src/main/res/drawable/ic_camera_dialog.xml
  android/app/src/main/res/drawable/ic_location_dialog.xml
  android/app/src/main/res/layout/dialog_permission.xml
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/repository/PlaceRepository.kt
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 빅스💻, 6차 데모데이

#473 hotfix: 좋아요/싫어요 취소 시, 싫어요 취소해도 좋아요 통계 줄어드는 오류 수정
  backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
  backend/src/test/java/com/now/naaga/like/application/PlaceLikeServiceTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#465 feat: 장소의 좋아요/싫어요 개수 조회 API
  backend/src/main/java/com/now/naaga/common/config/WebConfig.java
  backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
  backend/src/main/java/com/now/naaga/like/application/dto/CountPlaceLikeCommand.java
  backend/src/main/java/com/now/naaga/like/presentation/PlaceLikeController.java
  backend/src/main/java/com/now/naaga/like/presentation/dto/PlaceLikeCountResponse.java
  backend/src/main/java/com/now/naaga/placestatistics/application/PlaceStatisticsService.java
  backend/src/main/java/com/now/naaga/placestatistics/application/dto/FindPlaceStatisticsByPlaceIdCommand.java
  backend/src/test/java/com/now/naaga/like/application/PlaceLikeServiceTest.java
  backend/src/test/java/com/now/naaga/like/presentation/PlaceLikeControllerTest.java
  backend/src/test/java/com/now/naaga/placestatistics/application/PlaceStatisticsServiceTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#462 feat: 좋아요/싫어요 등록 API 구현
  backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
  backend/src/main/java/com/now/naaga/like/application/dto/ApplyLikeCommand.java
  backend/src/main/java/com/now/naaga/like/domain/PlaceLike.java
  backend/src/main/java/com/now/naaga/like/domain/PlaceLikeType.java
  backend/src/main/java/com/now/naaga/like/exception/PlaceLikeExceptionType.java
  backend/src/main/java/com/now/naaga/like/presentation/PlaceLikeController.java
  backend/src/main/java/com/now/naaga/like/presentation/dto/ApplyPlaceLikeRequest.java
  backend/src/main/java/com/now/naaga/like/presentation/dto/PlaceLikeResponse.java
  backend/src/main/java/com/now/naaga/placestatistics/application/PlaceStatisticsService.java
  backend/src/main/java/com/now/naaga/placestatistics/application/dto/PlusLikeCommand.java
  backend/src/main/java/com/now/naaga/placestatistics/domain/PlaceStatistics.java
  backend/src/test/java/com/now/naaga/like/application/PlaceLikeServiceTest.java
  backend/src/test/java/com/now/naaga/like/domain/PlaceLikeTypeTest.java
  backend/src/test/java/com/now/naaga/like/presentation/PlaceLikeControllerTest.java
  backend/src/test/java/com/now/naaga/placestatistics/application/PlaceStatisticsServiceTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#469 feat: 나의 좋아요/싫어요 여부 조회 API 구현
  backend/src/main/java/com/now/naaga/like/application/PlaceLikeService.java
  backend/src/main/java/com/now/naaga/like/application/dto/CheckMyPlaceLikeCommand.java
  backend/src/main/java/com/now/naaga/like/domain/MyPlaceLikeType.java
  backend/src/main/java/com/now/naaga/like/presentation/PlaceLikeController.java
  backend/src/main/java/com/now/naaga/like/presentation/dto/CheckMyPlaceLikeResponse.java
  backend/src/test/java/com/now/naaga/like/application/PlaceLikeServiceTest.java
  backend/src/test/java/com/now/naaga/like/domain/MyPlaceLikeTypeTest.java
  backend/src/test/java/com/now/naaga/like/presentation/PlaceLikeControllerTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#460 feat: 쪽지 단건 조회 api 구현
  backend/src/main/java/com/now/naaga/game/exception/GameExceptionType.java
  backend/src/main/java/com/now/naaga/letter/application/LetterService.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/ReadLetterLogService.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterLogCreateCommand.java
  backend/src/main/java/com/now/naaga/letter/exception/LetterException.java
  backend/src/main/java/com/now/naaga/letter/exception/LetterExceptionType.java
  backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
  backend/src/main/java/com/now/naaga/letter/presentation/dto/LetterReadCommand.java
  backend/src/main/java/com/now/naaga/letter/presentation/dto/LetterResponse.java
  backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
  backend/src/test/java/com/now/naaga/letter/application/letterlog/ReadLetterLogServiceTest.java
  backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
  backend/src/test/resources/truncate.sql
Labels: 🍀 백엔드, D-0, 6차 데모데이

#461 feat:플레이어의 주변 쪽지 조회api 구현
  backend/src/main/java/com/now/naaga/letter/application/LetterService.java
  backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
  backend/src/main/java/com/now/naaga/letter/presentation/dto/FindNearByLetterCommand.java
  backend/src/main/java/com/now/naaga/letter/presentation/dto/NearByLetterResponse.java
  backend/src/main/java/com/now/naaga/letter/repository/LetterRepository.java
  backend/src/test/java/com/now/naaga/common/fixture/PositionFixture.java
  backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
  backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#477 feat: 게임중 읽은/작성한 쪽지를 조회 api 구현
  backend/src/main/java/com/now/naaga/letter/application/letterlog/ReadLetterLogService.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/WriteLetterLogService.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/LetterByGameCommand.java
  backend/src/main/java/com/now/naaga/letter/domain/letterlog/ReadLetterLog.java
  backend/src/main/java/com/now/naaga/letter/domain/letterlog/WriteLetterLog.java
  backend/src/main/java/com/now/naaga/letter/presentation/LetterLogController.java
  backend/src/main/java/com/now/naaga/letter/presentation/LogType.java
  backend/src/main/java/com/now/naaga/letter/repository/letterlog/ReadLetterLogRepository.java
  backend/src/main/java/com/now/naaga/letter/repository/letterlog/WriteLetterLogRepository.java
  backend/src/test/java/com/now/naaga/letter/presentation/LetterLogControllerTest.java
  backend/src/test/resources/truncate.sql
Labels: 🍀 백엔드, D-0, 6차 데모데이

#480 feat: 내 주변 100m 내의 쪽지들을 조회하는 기능 구현
  android/app/src/main/java/com/now/naaga/data/mapper/LetterMapper.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultLetterRepository.kt
  android/app/src/main/java/com/now/naaga/di/RepositoryModule.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/NaverMapSettingDelegate.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/res/drawable/ic_closed_letter.xml
  android/app/src/main/res/drawable/ic_open_letter.xml
  android/domain/src/main/java/com/now/domain/model/letter/ClosedLetter.kt
  android/domain/src/test/java/com/now/domain/model/ClosedLetterTest.kt
Labels: 🦄 안드로이드, D-1, 크롱🦖, 6차 데모데이

#492 hotfix: PlaceLikeType 변수명을 API 명세에 맞춰 변경
  backend/src/main/java/com/now/naaga/like/application/dto/ApplyLikeCommand.java
  backend/src/main/java/com/now/naaga/like/presentation/dto/ApplyPlaceLikeRequest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#463 feat: 쪽지 등록 및 기록 API 구현
  backend/src/main/java/com/now/naaga/game/application/GameService.java
  backend/src/main/java/com/now/naaga/game/application/dto/FindGameInProgressCommand.java
  backend/src/main/java/com/now/naaga/game/exception/GameExceptionType.java
  backend/src/main/java/com/now/naaga/game/repository/GameRepository.java
  backend/src/main/java/com/now/naaga/letter/application/LetterFindService.java
  backend/src/main/java/com/now/naaga/letter/application/LetterService.java
  backend/src/main/java/com/now/naaga/letter/application/WriteLetterLogCreateService.java
  backend/src/main/java/com/now/naaga/letter/application/dto/CreateLetterCommand.java
  backend/src/main/java/com/now/naaga/letter/application/dto/FindLetterByIdCommand.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/WriteLetterLogService.java
  backend/src/main/java/com/now/naaga/letter/application/letterlog/dto/WriteLetterLogCreateCommand.java
  backend/src/main/java/com/now/naaga/letter/presentation/LetterController.java
  backend/src/main/java/com/now/naaga/letter/presentation/LetterLogController.java
  backend/src/main/java/com/now/naaga/letter/presentation/dto/LetterRequest.java
  backend/src/test/java/com/now/naaga/letter/application/LetterServiceTest.java
  backend/src/test/java/com/now/naaga/letter/presentation/LetterControllerTest.java
Labels: 🍀 백엔드, D-0, 6차 데모데이

#487 refactor: 에러처리 로직 변경
  android/app/src/main/java/com/now/naaga/data/throwable/DataThrowable.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
  android/app/src/main/java/com/now/naaga/util/extension/ContextExt.kt
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 빅스💻, 6차 데모데이

#494 f eat: 모험 기록 상세 페이지 뷰 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/mapper/OpenLetterMapper.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultLetterRepository.kt
  android/app/src/main/java/com/now/naaga/data/throwable/DataThrowable.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/AdventureDetailActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/AdventureDetailUiState.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/AdventureDetailViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/recyclerview/LetterAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/recyclerview/LetterViewHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/viewpager/ViewPagerAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/viewpager/ViewPagerHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/recyclerview/AdventureHistoryViewHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/OpenLetterMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/OpenLetterUiModel.kt
  android/app/src/main/java/com/now/naaga/util/extension/LifeCycleOwnerExt.kt
  android/app/src/main/java/com/now/naaga/util/extension/ResponseExt.kt
  android/app/src/main/java/com/now/naaga/util/extension/ViewExt.kt
  android/app/src/main/res/drawable/rect_red_white_radius_small.xml
  android/app/src/main/res/layout/activity_adventure_detail.xml
  android/app/src/main/res/layout/item_letter.xml
  android/app/src/main/res/layout/item_view_pager.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/now/naaga/AdventureDetailViewModelTest.kt
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 6차 데모데이

#495 feat: 좋아요 싫어요 기능 제작
  android/app/src/main/java/com/now/naaga/data/mapper/PlaceMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/LikeCountDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/PreferenceDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/PreferenceStateDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/PreferenceView.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/NaverMapSettingDelegate.kt
  android/app/src/main/res/drawable/ic_dislike_selected.xml
  android/app/src/main/res/drawable/ic_dislike_unselected.xml
  android/app/src/main/res/drawable/ic_like_selected.xml
  android/app/src/main/res/drawable/ic_like_unselected.xml
  android/app/src/main/res/drawable/selector_dislike.xml
  android/app/src/main/res/drawable/selector_like.xml
  android/app/src/main/res/layout/activity_adventure_result.xml
  android/app/src/main/res/layout/custom_preference_view.xml
  android/app/src/main/res/values/attrs.xml
  android/app/src/test/java/com/now/naaga/AdventureResultViewModelTest.kt
  android/domain/src/main/java/com/now/domain/model/Preference.kt
  android/domain/src/main/java/com/now/domain/model/PreferenceCount.kt
  android/domain/src/main/java/com/now/domain/model/PreferenceState.kt
  android/domain/src/main/java/com/now/domain/repository/PlaceRepository.kt
Labels: 🦄 안드로이드, D-1, 뽀또🍪, 6차 데모데이

#478 feat: 쪽지 등록기능 구현
  android/app/src/main/java/com/now/naaga/data/mapper/PlayerMapper.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultLetterRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/LetterSendDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/util/extension/ViewExt.kt
  android/app/src/main/res/drawable/ic_letter_received.xml
  android/app/src/main/res/drawable/ic_letter_send.xml
  android/app/src/main/res/drawable/ic_message_send.xml
  android/app/src/main/res/layout/activity_on_adventure.xml
  android/app/src/main/res/layout/dialog_send_letter.xml
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, D-1, 빅스💻, 6차 데모데이

#493 feat: 쪽지 단건 조회 구현
  android/app/src/main/java/com/now/naaga/data/mapper/LetterMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/LetterPreviewMapper.kt
  android/app/src/main/java/com/now/naaga/data/mapper/OpenLetterMapper.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/LetterDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/LetterPreviewDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/LetterService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultLetterRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/AdventureDetailActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/AdventureDetailUiState.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/AdventureDetailViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/recyclerview/LetterAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/recyclerview/LetterViewHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/viewpager/ViewPagerAdapter.kt
  android/app/src/main/java/com/now/naaga/presentation/adventuredetail/viewpager/ViewPagerHolder.kt
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/LetterReadDialog.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/NaverMapSettingDelegate.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/LetterMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/mapper/OpenLetterMapper.kt
  android/app/src/main/java/com/now/naaga/presentation/uimodel/model/LetterUiModel.kt
  android/app/src/main/java/com/now/naaga/util/extension/ClickListenerExt.kt
  android/app/src/main/java/com/now/naaga/util/singleclickevent/OnSingleClickListener.kt
  android/app/src/main/res/drawable/ic_closed_letter.xml
  android/app/src/main/res/drawable/ic_letter.xml
  android/app/src/main/res/drawable/ic_letter_preview.xml
  android/app/src/main/res/layout/dialog_read_letter.xml
  android/app/src/test/java/com/now/naaga/AdventureDetailViewModelTest.kt
  android/domain/src/main/java/com/now/domain/model/Coordinate.kt
  android/domain/src/main/java/com/now/domain/model/letter/ClosedLetter.kt
  android/domain/src/main/java/com/now/domain/model/letter/Letter.kt
  android/domain/src/main/java/com/now/domain/model/letter/LetterPreview.kt
  android/domain/src/main/java/com/now/domain/repository/LetterRepository.kt
  android/domain/src/test/java/com/now/domain/model/ClosedLetterTest.kt
Labels: 🦄 안드로이드, D-0, 크롱🦖, 빅스💻, 6차 데모데이

#504 fix: 게임 결과 뷰에서 뷰들이 겹치는 문제 해결
  android/app/src/main/res/layout/activity_adventure_result.xml
Labels: 🦄 안드로이드, D-0, 뽀또🍪, 6차 데모데이

#509 feat: 쪽지를 불러오는 통신 주기 변경
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
Labels: 🦄 안드로이드, D-0, 크롱🦖, 6차 데모데이

#514 feat: 운영 서버 무중단 배포 파이프라인 적용
  .github/workflows/backend_prod_merge_workflow.yml
  backend/Dockerfile-prod
Labels: 🍀 백엔드, D-0, 6차 데모데이

#517 fix: 힌트 개수가 null로 보이는 버그 수정
  android/app/src/main/java/com/now/naaga/presentation/common/dialog/DialogType.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/DistinctChildLiveData.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
Labels: 🦄 안드로이드, D-0, 빅스💻, 6차 데모데이

#522 feat: 앱 gradle 설정 변경
  android/app/build.gradle
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 6차 데모데이
