Repository woowacourse-teams/2023-naaga, pull requests merged in 2023-09, with the labels that each got.

#301 feat: 장소 업로드 기능 구현
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
  android/app/src/main/res/values/strings.xml
Labels: 🦄 안드로이드, 5차 데모데이, D-1

#302 fix: 위치관련 버그 수정
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
  android/app/src/main/res/layout/activity_upload.xml
Labels: 🦄 안드로이드, 5차 데모데이, D-0

#311 refactor: 안드로이드 ci branch 수정
  .github/workflows/android_ci.yml
Labels: 🦄 안드로이드, 5차 데모데이

#312 refactor: 네트워크 작업 코루틴으로 변경
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/RankService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultRankRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
  android/app/src/main/java/com/now/naaga/util/ResponseUtil.kt
  android/domain/src/main/java/com/now/domain/repository/RankRepository.kt
Labels: 🦄 안드로이드, 5차 데모데이

#307 refactor: ViewModel이 Application을 참조하지 않도록 변경
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-0

#320 refactor: remote top level에 필요없는 .idea 파일 삭제 및 .gitignore 추가
  .gitignore
Labels: 🦄 안드로이드

#328 refactor: Login 뷰에서 진행하는 네트워크 작업 코루틴으로 변경
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AuthService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModel.kt
  android/domain/src/main/java/com/now/domain/repository/AuthRepository.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-0

#323 refactor: my page뷰에서 진행하는 네트워크 작업 코루틴으로 변경
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/PlaceService.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/StatisticsService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultStatisticsRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
  android/domain/src/main/java/com/now/domain/repository/PlaceRepository.kt
  android/domain/src/main/java/com/now/domain/repository/StatisticsRepository.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-1, 빅스💻

#331 feat: Setting 뷰 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingViewModel.kt
  android/app/src/main/res/drawable/ic_setting.xml
  android/app/src/main/res/layout/activity_my_page.xml
  android/app/src/main/res/layout/activity_setting.xml
Labels: 🦄 안드로이드, 5차 데모데이, D-0, 크롱🦖

#317 fix: History 뷰의 리사이클러뷰 image 오류 문제 해결
  android/app/src/main/res/layout/activity_adventure_history.xml
  android/app/src/main/res/layout/item_history.xml
Labels: 🦄 안드로이드, 5차 데모데이, D-1, 빅스💻

#315 refactor: Adventure 도메인에 해당하는 네트워크 작업 코루틴으로 변경
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AdventureService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
  android/domain/src/main/java/com/now/domain/repository/AdventureRepository.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-0, 뽀또🍪

#308 feat: 장소 업로드 시 로딩 창이 뜨는 기능 구현
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadStatus.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
  android/app/src/main/java/com/now/naaga/util/Event.kt
  android/app/src/main/java/com/now/naaga/util/MutableSingleLiveData.kt
  android/app/src/main/java/com/now/naaga/util/SingleLiveData.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-0, 뽀또🍪

#333 fix: 마이페이지 글자 깨지는 오류 수정
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewHolder.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-2, 크롱🦖

#340 feat: AdventureHistoryViewModel 테스트 추가
  android/app/build.gradle
  android/app/src/test/java/com/now/naaga/AdventureHistoryViewModelTest.kt
  android/app/src/test/java/com/now/naaga/getOrAwaitValue.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-2, 크롱🦖

#335 feat: 회원 탈퇴 기능 구현
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AuthService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/now/naaga/util/KakaoLoginUtil.kt
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/repository/AuthRepository.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-2, 크롱🦖

#341 feat: 로그아웃 기능 구현
  android/app/src/main/java/com/now/naaga/data/local/AuthDataSource.kt
  android/app/src/main/java/com/now/naaga/data/local/DefaultAuthDataSource.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitUtil.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/service/AuthService.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/now/naaga/util/ResponseUtil.kt
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/com/now/domain/repository/AuthRepository.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-2, 뽀또🍪

#349 refactor: 리포지터리에 의존성 주입 라이브러리 적용
  android/app/build.gradle
  android/app/src/main/java/com/now/naaga/NaagaApplication.kt
  android/app/src/main/java/com/now/naaga/di/RepositoryModule.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventurehistory/AdventureHistoryViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/adventureresult/AdventureResultViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/beginadventure/BeginAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/login/LoginViewModelFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/mypage/MyPageViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/onadventure/OnAdventureViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/rank/RankViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/upload/UploadViewModel.kt
  android/build.gradle
Labels: 🦄 안드로이드, 5차 데모데이, D-0, 뽀또🍪, 빅스💻

#352 refactor: datasource 의존성 주입 라이브러리 적용
  android/app/src/main/java/com/now/naaga/di/DataSourceModule.kt
  android/app/src/main/java/com/now/naaga/di/RepositoryModule.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-0, 뽀또🍪, 빅스💻

#353 refactor: retrofit 의존성 주입 라이브러리 적용
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/ServicePool.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAdventureRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultAuthRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultPlaceRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultRankRepository.kt
  android/app/src/main/java/com/now/naaga/data/repository/DefaultStatisticsRepository.kt
  android/app/src/main/java/com/now/naaga/di/RepositoryModule.kt
  android/app/src/main/java/com/now/naaga/di/ServiceModule.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-0, 뽀또🍪, 빅스💻

#346 feat: 자동로그인 기능 구현 및 스플래시 분리
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/now/naaga/data/firebase/analytics/ServerErrorNames.kt
  android/app/src/main/java/com/now/naaga/data/local/DefaultAuthDataSource.kt
  android/app/src/main/java/com/now/naaga/data/remote/dto/RefreshTokenDto.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/AuthInterceptor.kt
  android/app/src/main/java/com/now/naaga/data/remote/retrofit/RetrofitFactory.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/now/naaga/presentation/splash/SplashViewModel.kt
  android/app/src/main/res/drawable/ic_naaga_logo.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/test/java/com/now/naaga/ExampleUnitTest.kt
  android/app/src/test/java/com/now/naaga/getOrAwaitValue.kt
  android/domain/src/main/java/com/now/domain/repository/AuthRepository.kt
Labels: 🦄 안드로이드, 5차 데모데이, D-2, 뽀또🍪
